# - ignore: {name: Use let}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules

- ignore:
    name: Avoid lambda

- ignore:
    name: Use section

- ignore:
    name: Use fmap
